'use client';

import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Loader2, Sparkles, Leaf, Recycle, TrendingUp, Calendar, Plus } from 'lucide-react';
import { Navbar } from '@/components/navbar';
import { AppShell } from '@/components/app-shell';
import { ProtectedRoute } from '@/components/protected-route';
import { useAuth } from '@/components/auth-provider';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from '@/components/ui/dialog';
import { fetchReports, fetchMatches } from '@/lib/data';
import { aiGenerateReport } from '@/lib/ai-service';
import type { Report, Match } from '@/lib/types';
import { toast } from 'sonner';
import jsPDF from 'jspdf';

function ReportsContent() {
  const { user } = useAuth();
  const [reports, setReports] = useState<Report[]>([]);
  const [matches, setMatches] = useState<Match[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [reportType, setReportType] = useState('esg');
  const [period, setPeriod] = useState('Q3 2025');

  useEffect(() => {
    (async () => {
      if (!user) return;
      try {
        const [r, m] = await Promise.all([fetchReports(user.id), fetchMatches()]);
        setReports(r);
        setMatches(m);
      } finally { setLoading(false); }
    })();
  }, [user]);

  const handleGenerate = async () => {
    if (!user) return;
    setGenerating(true);
    try {
      const co2Saved = matches.reduce((s, m) => s + Number(m.co2_saved_kg), 0);
      const wasteDiverted = matches.reduce((s, m) => s + Number(m.landfill_diverted_kg), 0);
      const matchesCount = matches.length;

      const reportText = await aiGenerateReport({
        orgName: user.organization || user.full_name,
        period,
        co2SavedKg: co2Saved,
        wasteDivertedKg: wasteDiverted,
        circularityScore: user.circularity_score,
        matchesCount,
        reportType,
      });

      // Generate PDF
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      let y = 20;

      // Header
      doc.setFillColor(11, 79, 63);
      doc.rect(0, 0, pageWidth, 30, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('NexLoop AI', 14, 16);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('AI-Powered Industrial Symbiosis', 14, 23);

      // Title
      doc.setTextColor(40, 40, 40);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(`${reportType.toUpperCase()} Report`, 14, 45);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(`${user.organization || user.full_name} — ${period}`, 14, 52);

      // Body
      doc.setFontSize(10);
      const lines = doc.splitTextToSize(reportText, pageWidth - 28);
      doc.text(lines, 14, 62);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text(`Generated by NexLoop AI on ${new Date().toLocaleDateString()}`, 14, doc.internal.pageSize.getHeight() - 10);

      doc.save(`nexloop-${reportType}-${period.replace(/\s/g, '-').toLowerCase()}.pdf`);
      toast.success('Report generated and downloaded');
      setDialogOpen(false);
    } catch (e) {
      toast.error('Failed to generate report');
      console.error(e);
    } finally {
      setGenerating(false);
    }
  };

  const reportTypeBadge = (type: string) => {
    const colors: Record<string, string> = {
      esg: 'bg-blue-500/15 text-blue-600 dark:text-blue-400',
      sustainability: 'bg-accent/15 text-accent',
      impact: 'bg-purple-500/15 text-purple-600 dark:text-purple-400',
      circularity: 'bg-primary/15 text-primary',
    };
    return colors[type] || '';
  };

  return (
    <AppShell>
      <div className="space-y-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h1 className="font-display text-2xl md:text-3xl font-bold">Reports</h1>
            <p className="text-muted-foreground text-sm mt-1">AI-generated ESG and sustainability reports</p>
          </div>
          <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
            <DialogTrigger asChild>
              <Button size="sm" className="eco-gradient text-primary-foreground">
                <Plus className="h-4 w-4 mr-1.5" /> Generate Report
              </Button>
            </DialogTrigger>
            <DialogContent className="glass-strong">
              <DialogHeader>
                <DialogTitle>Generate AI Report</DialogTitle>
                <CardDescription>Create a new sustainability report with AI-generated narrative</CardDescription>
              </DialogHeader>
              <div className="space-y-4 py-2">
                <div className="space-y-2">
                  <Label>Report Type</Label>
                  <Select value={reportType} onValueChange={setReportType}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="esg">ESG Report</SelectItem>
                      <SelectItem value="sustainability">Sustainability Report</SelectItem>
                      <SelectItem value="impact">Impact Report</SelectItem>
                      <SelectItem value="circularity">Circularity Assessment</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="period">Period</Label>
                  <Input id="period" value={period} onChange={(e) => setPeriod(e.target.value)} placeholder="Q3 2025" />
                </div>
                <div className="glass rounded-lg p-3 text-xs text-muted-foreground">
                  <p className="flex items-center gap-1.5"><Sparkles className="h-3 w-3 text-accent" /> AI will analyze your matches, CO2 savings, and circularity score to generate a narrative report.</p>
                  <p className="mt-1.5">AI generates a narrative report via the centralized client (Groq / Llama 3.3 70B).</p>
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button>
                <Button onClick={handleGenerate} disabled={generating} className="eco-gradient text-primary-foreground">
                  {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <>Generate & Download <Download className="ml-1.5 h-4 w-4" /></>}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>

        {/* Quick stats */}
        <div className="grid grid-cols-3 gap-4">
          <Card className="glass border-border/40"><CardContent className="pt-6 flex items-center gap-3"><div className="h-10 w-10 rounded-xl eco-gradient flex items-center justify-center"><Leaf className="h-5 w-5 text-primary-foreground" /></div><div><p className="text-sm text-muted-foreground">CO2 Saved</p><p className="font-display text-xl font-bold">{(matches.reduce((s, m) => s + Number(m.co2_saved_kg), 0) / 1000).toFixed(1)}T</p></div></CardContent></Card>
          <Card className="glass border-border/40"><CardContent className="pt-6 flex items-center gap-3"><div className="h-10 w-10 rounded-xl eco-gradient flex items-center justify-center"><Recycle className="h-5 w-5 text-primary-foreground" /></div><div><p className="text-sm text-muted-foreground">Waste Diverted</p><p className="font-display text-xl font-bold">{(matches.reduce((s, m) => s + Number(m.landfill_diverted_kg), 0) / 1000).toFixed(1)}T</p></div></CardContent></Card>
          <Card className="glass border-border/40"><CardContent className="pt-6 flex items-center gap-3"><div className="h-10 w-10 rounded-xl eco-gradient flex items-center justify-center"><TrendingUp className="h-5 w-5 text-primary-foreground" /></div><div><p className="text-sm text-muted-foreground">Matches</p><p className="font-display text-xl font-bold">{matches.length}</p></div></CardContent></Card>
        </div>

        {/* Reports list */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {loading ? (
            <div className="col-span-full flex justify-center py-12"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>
          ) : reports.length === 0 ? (
            <Card className="glass border-border/40 col-span-full">
              <CardContent className="py-12 text-center">
                <FileText className="h-12 w-12 text-muted-foreground/40 mx-auto mb-3" />
                <p className="text-muted-foreground">No reports yet. Generate your first AI-powered report above.</p>
              </CardContent>
            </Card>
          ) : reports.map((r, i) => (
            <motion.div key={r.id} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.08 }}>
              <Card className="glass border-border/40 card-hover h-full">
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <Badge variant="secondary" className={`text-xs uppercase ${reportTypeBadge(r.report_type)}`}>{r.report_type}</Badge>
                    <div className="flex items-center gap-1 text-xs text-muted-foreground"><Calendar className="h-3 w-3" />{r.period}</div>
                  </div>
                  <CardTitle className="text-sm mt-2 line-clamp-2">{r.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-xs text-muted-foreground line-clamp-3 mb-3">{r.summary}</p>
                  <div className="grid grid-cols-2 gap-2 mb-3">
                    <div className="glass rounded-lg p-2"><div className="text-xs text-muted-foreground">CO2 Saved</div><div className="text-sm font-medium text-accent">{Number(r.co2_saved_kg).toLocaleString()} kg</div></div>
                    <div className="glass rounded-lg p-2"><div className="text-xs text-muted-foreground">Diverted</div><div className="text-sm font-medium">{Number(r.waste_diverted_kg).toLocaleString()} kg</div></div>
                  </div>
                  <Button variant="outline" size="sm" className="w-full glass" onClick={() => {
                    const doc = new jsPDF();
                    doc.text(r.summary, 14, 20);
                    doc.save(`${r.title}.pdf`);
                    toast.success('Report downloaded');
                  }}>
                    <Download className="h-3.5 w-3.5 mr-1.5" /> Download PDF
                  </Button>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </AppShell>
  );
}

export default function ReportsPage() {
  return (
    <div className="min-h-screen">
      <Navbar />
      <ProtectedRoute>
        <ReportsContent />
      </ProtectedRoute>
    </div>
  );
}
